engines:
    pep8:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
            - python
ratings:
    paths:
        - "**.py"
exclude_paths:
- docs/*
- ruruki/test_utils/*
