engines:
    radon: 
        enabled: true
    pep8:
        enabled: false
    duplication:
        enabled: false
        config:
            languages:
            - python
ratings:
    paths:
        - "**.py"
exclude_paths:
- docs/*
- ruruki/test_utils/*
