engines:
    radon: 
        enabled: true
        config: 
            python_version: 2
            threshold: "D"
    pep8:
        enabled: false
    duplication:
        enabled: false
        config:
            languages:
            - python
ratings:
    paths:
        - "**.py"
exclude_paths:
- docs/*
- ruruki/test_utils/*
- ruruki/tests/*
