language: python
python:
  - "2.7"
install:
    # - pip install coveralls
  - pip install tox-travis
script:
  - mkdir docs/_static
  - tox
# after_success: coveralls
notifications:
  email:
    recipients:
      - jenmud@gmail.com
      - jenmud@optiver.com.au
    on_success: change
    on_failure: always
