language: python
python:
  - "2.7"
install:
  - pip install tox-travis
script: tox
# whitelist branches to build
# branches:
#   - master
notifications:
  email:
    recipients:
      - jenmud@gmail.com
      - jenmud@optiver.com.au
    on_success: change
    on_failure: always
